### ISSUE TITLE
Init binary isn't able to get properties like hardware from /proc/cpuinfo

### ISSUE THREAD

**Issue by TBM13** [Exynos3475/android_device_samsung_j2lte#2]
For some reason, the nougat init binary can't get ro.hardware from /proc/cpuinfo even when it's declared there, so it sets it to the default value: unknown

This means that it searches for files in the ramdisk like init.unknown.rc instead of init.universal3475.rc

A temporary solution for this would be to rename (or copy) the files to, for example, init.unknown.rc

**Comment by TBM13** [comment]
Same happens with ON5 Pro nougat init binary; this explains why it booted just fine on the ON5 Pro.

**Comment by TBM13** [comment]
I successfully booted LOS 14.1 on the j2lte by doing that temporary solution.

**Comment by TBM13** [comment]
I'm pretty sure this could also work on the J1XLTE, which seems to have the same issue: A guy with that phone will build and test.

**Comment by TBM13** [comment]
I used ON5 Pro cm-14.1-20180513 tree because it's more stable.
This is what is working:
WiFI
Touchscreen
Vibration
Sound
Accelerometer
Proximity sensor
MTP
Headphones
Offline charging
Bluetooth

Things that arent' working:
GPS
Camera

Things that i didn't tested:
RIL (SIM, telephony). IMEI is unknown so i suppose it isn't working (related to the same unknown problem of ro.hardware?

**Comment by TBM13** [comment]
Seems like the ROM can't also find the baseband version, because it's "Unknown".

**Comment by ghost** [comment]
> Seems like the ROM can't also find the baseband version, because it's "Unknown".

That's because RIL was borked.

**Comment by bengris32** [comment]
[Fixed](https://github.com/Exynos3475/android_kernel_samsung_exynos3475/commit/38fbda34d993e0b306188d14c3d854223d3a3c57)

**Comment by ghost** [comment]
Fixed https://github.com/Exynos3475/android_kernel_samsung_exynos3475/commit/38fbda34d993e0b306188d14c3d854223d3a3c57
